@startuml
package “ユーザ集約” {
  ユーザ  *-- “0..*” 経歴
  ユーザ  *-- “1..*” スキル
}
object ユーザ {
  ID
  名前
  メールアドレス
  パスワード
  List<スキル>
  自己紹介
  List<経歴>
}
object 経歴 {
  ID
  詳細
  始まりの年
  終了した年
}
object スキル {
  ID
  タグID
  評価
  年数
}
note top of ユーザ
  必須
     - 名前 : 255文字以内
     - メールアドレス : 255文字以内
     - ・パスワード : 12文字以上, 英数字それぞれ最低1文字以上
     - スキル1つ以上
   任意
     - 自己紹介 : 2000字以内
     - 経歴: 複数
end note
note bottom of 経歴
  - 詳細: 1000字以内
  - 始まりの年: 1970年以上のint型
  - 終了の年: 1970年以上のint型、startYearよりも大きい数字
end note
note bottom of スキル
  - 選択式
  - 評価 : 1~5
  - 年数 : ０以上のint型(5年まで)
end note


package “メンター募集集約” {
  メンター募集 “0..*” --  ユーザ
}
object メンター募集 {
  ID
  タイトル
  カテゴリ
  契約タイプ
  相談形式
  詳細
  予算from
  予算to
  応募期間
  ステータス
  List<タグID>
  メンターユーザID
}
note left of メンター募集
  必須
    - タイトル: 255文字以内
    - カテゴリ: 1つ
　　- プログラミング
　　- マーケティング
　　- デザイン
　　- ライティング
　　- 動画・映像
　　- ビジネス
　　- 語学
　　- ライフスタイル
    - 相談形式: 単発or継続
    - 相談方式: チャットorビデオ通話
    - 詳細: 2000文字以内
    - 予算: from円~to円, 1000円以上の数値
    - 応募期間: 1日単位, 最大14日後まで可能
    - ステータス: 公開or中止
  任意
    - タグ: 複数OK
end note

package “メンター提案集約” {
  メンター募集 -- “0..*”  メンター提案
  メンター提案 "0..*" -- ユーザ
}
object メンター提案 {
  ID
  内容
  メンターID
  メンター募集ID
}
note bottom of メンター提案
  - 内容: 2000文字以内
  - 提案できるのはスキルを5個以上持つユーザのみ
end note
package “メンタープラン集約” {
  ユーザ -- “0..*” メンタープラン
}
object メンタープラン {
  ID
  タイトル
  カテゴリ
  List<タグID>
  内容
  ステータス
  金額
  相談方式
  相談形式
  メンターID
}
note right of メンタープラン
  必須
    - タイトル: 255文字以内
    - カテゴリ: 1つのみ
    - タグ: 5個まで
    - 内容: 2000文字以内
    - ステータス: 公開or中止
    - 金額
    - 相談形式: 単発or継続
  任意
    - 相談方式: チャットorビデオ電話
end note

package ” 契約リクエスト Aggreate”{
  契約リクエスト -- "1" ユーザ
  契約リクエスト"0..*" -- メンタープラン
}

object 契約リクエスト {
  ID
  メッセージ
  メンターID
  リクエスト時の金額
  プランID
}
note right of 契約リクエスト
  メッセージ: 500文字
  リクエスト時の金額: リクエストが送られたタイミングのプランの金額(プランの金額変更に備えて)
end note


package ” 契約 Aggreate”{
  契約 “1..*” -- メンタープラン
  ユーザ “1” -- 契約
}
object 契約 {
  ID
  メンターID
  メンタープランID
  メッセージ
}
package “タグ Aggreate”  {
  スキル “1..*” -- タグ
  メンター募集 -- “0..*” タグ
  メンタープラン -- “0..*” タグ
}
object タグ {
  ID
  タグ名
}
@enduml
